import os
import textwrap
import time
from dataclasses import dataclass

from typing import Callable

import anthropic
from anthropic.types import MessageParam
from dotenv import load_dotenv

EXAMPLES: list[tuple[str, str]] = [
    ("The login button does nothing on mobile Safari.", "frontend"),
    ("POST /api/orders returns 500 with NullPointerException.", "backend"),
    ("Last month's sales data is missing from the report.", "data"),
]
POLICY = """
You are a bug classifier for a software product. Classify bugs into one of three categories:

- frontend: Issues with the user interface, browser behaviour, visual rendering, 
  or client-side interactions (clicks, forms, navigation, layout).
- backend: Issues with APIs, server errors, authentication, business logic, 
  or server-side processing.
- data: Issues where the application works correctly but the data is wrong, 
  missing, outdated, or inconsistent.

When a bug could fit multiple categories, choose the one that describes 
where the root cause most likely lives.
"""

COT_INSTRUCTIONS = """
Think step by step:
1. What is the user observing?
2. Where does the problem most likely originate — UI, server, or data?
3. Which category best fits based on the policy above?

After your reasoning, write your final answer on a new line in this exact format:
Answer: <one word>
"""

@dataclass
class PromptResult:
    """Stores the result of a single prompt variant API call.

    Attributes:
        variant_name: Label identifying the prompt style (e.g. 'zero_shot').
        prompt_used: The full prompt string that was sent to the API.
        output: The text the model returned.
        input_tokens: Number of tokens consumed by the prompt.
        output_tokens: Number of tokens generated by the model.
        latency_ms: Time taken for the API call in milliseconds.
    """
    variant_name: str
    prompt_used: str
    output: str
    input_tokens: int
    output_tokens: int
    latency_ms: float

    def cost_usd(self) -> float:
        """Calculate the cost of this API call in USD.

        Uses claude-haiku-4-5 pricing:
            $1.00 per million input tokens
            $5.00 per million output tokens
        """
        return (self.input_tokens * 1.0 + self.output_tokens * 5.0) / 1000000

    def to_dict(self) -> dict:
        """Return all fields as a dictionary, including the calculated cost."""
        return {"variant_name": self.variant_name,
                "prompt_used": self.prompt_used,
                "output": self.output,
                "input_tokens": self.input_tokens,
                "output_tokens": self.output_tokens,
                "latency_ms": self.latency_ms,
                "cost": self.cost_usd()
        }

def build_few_shot_prompt(new_input: str) -> str:
    """Build a few-shot prompt using the module-level EXAMPLES list.

    Formats each example as 'Ticket: <input> -> <label>' and appends
    the new input for the model to classify.

    Args:
        new_input: The bug description to classify.

    Returns:
        A prompt string containing examples followed by the new input.
    """
    examples_str = "\n".join(f'"Ticket:" "{inp}" -> {label}' for inp, label in EXAMPLES)

    return textwrap.dedent(f"""
"Classify each support ticket as: frontend / backend / data. Reply with the label only, no explanation."

{examples_str}

"Ticket:" "{new_input}" ->
""")


def build_cot_prompt(new_input: str) -> str:
    """Build a chain-of-thought prompt using the module-level POLICY and COT_INSTRUCTIONS.

    Instructs the model to reason step by step before stating its final answer
    in the format 'Answer: <one word>'.

    Args:
        new_input: The bug description to classify.

    Returns:
        A prompt string containing the policy, the request, and CoT instructions.
    """
    return textwrap.dedent(f"""
Policy: {POLICY}

Request: "{new_input}"

{COT_INSTRUCTIONS}""")

def run_variants(
        user_input: str,
        variants: list[tuple[str, Callable[[str], str]]]
) -> list[PromptResult]:
    """Run multiple prompt variants against the same input and return results.

    For each variant, builds the prompt, calls the Claude API, and records
    the output, token usage, cost, and latency.

    Args:
        user_input: The text to send to each variant.
        variants: List of (name, prompt_builder) pairs. Each prompt_builder
                  accepts the user_input string and returns a prompt string.

    Returns:
        A list of PromptResult objects, one per variant, in order.
    """
    load_dotenv()
    client = anthropic.Anthropic()
    results: list[PromptResult] = []

    for name, builder in variants:
        message: str = builder(user_input)
        prompt: list[MessageParam] = [
            {
                "role": "user",
                "content": message,
            }
        ]
        start_time: float = time.perf_counter()
        response = client.messages.create(
            model=os.environ["ANTHROPIC_MODEL_NAME"],
            max_tokens=512,
            temperature=0.0,
            system="You are a bug classifier. Always end your response with 'Answer: ' followed by exactly one word: frontend, backend, or data.",
            messages=prompt,
        )
        elapsed_time: float = (time.perf_counter() - start_time) * 1000
        results.append(PromptResult(
            variant_name=name,
            prompt_used=message,
            output=response.content[0].text,
            input_tokens=response.usage.input_tokens,
            output_tokens=response.usage.output_tokens,
            latency_ms=elapsed_time,
        ))

    return results

def print_summary_table(results: list[PromptResult]) -> None:
    """Print a formatted comparison table of all variant results.

    Displays variant name, token counts, cost, and latency in aligned columns,
    followed by the total experiment cost across all variants.

    Args:
        results: List of PromptResult objects to display.
    """
    headers: list[str] = ["VARIANT", "TOKEN IN", "TOKEN OUT", "COST USD", "LATENCY MS"]
    space: int = 13

    print(f"{headers[0]:<{space}} {headers[1]:<{space}} {headers[2]:<{space}} {headers[3]:<{space}} {headers[4]:<{space}}")
    for result in results:
        print(f"{result.variant_name:<{space}} {result.input_tokens:<{space}} {result.output_tokens:<{space}} ${result.cost_usd():<{space}.6f} {result.latency_ms:<{space}.3f}")

    total_cost: float = sum(r.cost_usd() for r in results)
    print(f"Total Experiment Cost: ${total_cost:.6f}")

if __name__ == "__main__":
    new_user_input: str = "Last month's sales figures are missing from the analytics dashboard."
    variants_list: list[tuple[str, Callable[[str], str]]] = [
        ("zero_shot", lambda inp: f"Classify this bug as frontend, backend, or data. Reply with one word only.\n\nBug: {inp}"),
        ("few_shot", lambda inp: build_few_shot_prompt(inp)),
        ("cot", lambda inp: build_cot_prompt(inp)),
    ]

    print_summary_table(run_variants(new_user_input, variants_list))
